

sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t kajekar/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true kajekar/docker-react npm run test
